apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: self-heal-demo
  namespace: argocd
spec:
  destination:
    namespace: self-heal-demo
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: guestbook-with-sub-directories
    repoURL: "https://github.com/shreyanshs7/argocd-example-apps-private.git"
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
