apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-demo
  namespace: argocd
spec:
  destination:
    namespace: sync-demo
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: sync-phases
    repoURL: "https://github.com/shreyanshs7/argocd-example-apps-private.git"
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
