apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: staging-

namespace: staging

resources:
- ../../base/service-1
- ../../base/service-2

labels:
- includeSelectors: true
  pairs:
    env: staging

patches:
  - path: service-1/deployment-patch.yaml
  - path: service-2/deployment-patch.yaml
