apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging-accounts
namePrefix: accounts-


resources:
- ../../base/accounts


patches:
  - path: patches/deployments/app-1.yaml
