apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-app-2
  namespace: thor-platform
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: service-app-2
  template:
    metadata:
      labels:
        app: service-app-2
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        name: service-app-2
        ports:
        - containerPort: 80
