apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: clusters-nameip-config
  envs:
  - configmaps/clusters-nameip-config.env

- name: url-config
  envs:
  - configmaps/url.env

resources:
  - services/app-1.yaml
  - services/app-2.yaml

  - deployments/app-1.yaml
  - deployments/app-2.yaml
