apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- accounts/namespace.yaml
- platform/namespace.yaml
- accounts/
- platform/


images:
- name: nginx
  newName: memcached
  newTag: latest
