apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- accounts/namespace.yaml
- platform/namespace.yaml
- accounts/
- platform/


images:
- name: memcached
  newName: memcached
  newTag: 1.6
- name: redis
  newName: redis
  newTag: 7.2