apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: app-2
  template:
    metadata:
      labels:
        app: app-2
    spec:
      containers:
      - image: python3:latest
        name: app-2
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: regcred
