apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        name: app-1
        envFrom:
          - configMapRef:
              name: configmap-1
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: regcred
