apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - image: nginx
        name: app-1
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: regcred
