apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - image: docker.io/shreyanshss7/demo-app:f6faf612a2bdc44b97d1333a68a37b5cb2d37926
        name: demo-app
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: regcred
