apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - image: docker.io/shreyanshss7/demo-app:87464a730b1bbdd6a3617eb92ddca9fc8355e82b
        name: demo-app
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: regcred
