apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - image: docker.io/shreyanshss7/demo-app:da3afbfdda3ed6da7d5eb2e4ac57f0ba3460db84
        name: demo-app
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: regcred
