apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - image: docker.io/shreyanshss7/demo-app:6289b7a9ad899c53c3021d9a1b70fb87a295ee2c
        name: demo-app
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: regcred
