apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - image: docker.io/shreyanshss7/demo-app:4f74cec30124c21ea8d2afd8444deca1ca43892d
        name: demo-app
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: regcred
