apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - image: docker.io/shreyanshss7/demo-app:69a46585617751910492becb8fcfda57850db5f2
        name: demo-app
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: regcred
