apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - image: docker.io/shreyanshss7/demo-app:ced54c3898a78fa1cb9a53d3d23c71e1cb33432a
        name: demo-app
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: regcred
