apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: kustomize-

resources:
- guestbook-ui-deployment.yaml
- guestbook-ui-svc.yaml
- demo-app-deployment.yaml
- demo-app-svc.yaml
images:
- name: docker.io/shreyanshss7/demo-app
  newName: docker.io/shreyanshss7/demo-app
  newTag: 1ef31de62954288e67c041b9fd46508b734ba4f9
