apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-app-1
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: service-app-1
  template:
    metadata:
      labels:
        app: service-app-1
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        name: service-app-1
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: regcred
----
apiVersion: v1	
kind: Service	
metadata:	
  name: service-app-1	
spec:	
  ports:	
  - port: 80	
    targetPort: 80	
  selector:	
    app: service-app-1
