apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-app-2
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: service-app-2
  template:
    metadata:
      labels:
        app: service-app-2
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        name: service-app-2
        ports:
        - containerPort: 80
----
apiVersion: v1	
kind: Service	
metadata:	
  name: service-app-2	
spec:	
  ports:	
  - port: 80	
    targetPort: 80	
  selector:	
    app: guestbook-ui
