apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-1
  namespace: argocd
spec:
  destination:
    namespace: application-1
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: v2/overlays/staging
    repoURL: "https://github.com/shreyanshs7/argocd-example-apps-private.git"
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
