apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespaces/thor-default.yaml
- namespaces/thor-platform.yaml
- ../../base/service-1
- ../../base/service-2
- ../../base/service-3

labels:
- includeSelectors: true
  pairs:
    env: thor


patches:
  - path: namespaces/thor-default.yaml
  - path: namespaces/thor-platform.yaml
  - path: service-1/deployment-patch.yaml
  - path: service-2/deployment-patch.yaml
  - path: service-3/deployment-patch.yaml
