apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging-platform
namePrefix: platform-

resources:
- ../../base/platform


patches:
  - path: patches/deployments/app-2.yaml
