name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          pushd demo-app
          docker build -t docker.io/${{ secrets.DOCKER_USERNAME }}/demo-app:${{ github.sha }} .
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/demo-app:${{ github.sha }}
          popd

      - name: Update Kustomize file
        run: |
          pushd kustomize-guestbook
          kustomize edit set image docker.io/${{ secrets.DOCKER_USERNAME }}/demo-app=docker.io/${{ secrets.DOCKER_USERNAME }}/demo-app:${{ github.sha }}
          popd

      # - name: Commit and push changes
      #   run: |
      #     git config user.name "GitHub Actions"
      #     git config user.email "shreyanshss7@gmail.com"
      #     git add -A
      #     git commit -m "Minor changes"
      #     git push
